=== vernik03/Greenhouse/out/production/Greenhouse/com/lab2/Flower.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Flower" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="soil">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="PODZOLIC|GROUND|SODDY_PODZOLIC"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="origin" type="xs:string"/>
                <xs:element name="visualParameters">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="stem_color">
                                <xs:simpleType>
                                    <xs:restriction base="xs:token">
                                        <xs:pattern value="#[\dA-F]{6}([\dA-F][\dA-F])?"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="leaf_color">
                                <xs:simpleType>
                                    <xs:restriction base="xs:token">
                                        <xs:pattern value="#[\dA-F]{6}([\dA-F][\dA-F])?"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="size">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="VERY_SMALL|SMALL|MEDIUM|BIG|VERY_BIG"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="growingTips">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="temperature" type="xs:float"/>
                            <xs:element name="is_photophilous" type="xs:boolean"/>
                            <xs:element name="watering" type="xs:float"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="multiplying">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="BY_LEAVES|BY_CUTTINGS|BY_SEEDS"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vernik03/Greenhouse/src/com/lab2/Flower.xml
<?xml version="1.0"?>
<Flower xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Flower.xsd">
    <name>Roze</name>
    <soil>PODZOLIC</soil>
    <origin>Ukraine</origin>
    <visualParameters>
        <stem_color>#FF0000</stem_color>
        <leaf_color>#00FFFF</leaf_color>
        <size>MIDDLE</size>
    </visualParameters>
    <growingTips>
        <temperature>15</temperature>
        <is_photophilous>true</is_photophilous>
        <Watering>10</Watering>
    </growingTips>
    <multiplying>BY_CUTTINGS</multiplying>
</Flower>
