=== vernik03/Greenhouse/src/com/lab2/Flowers.xsd
<?xml version="1.1" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="Flowers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Flower">
                    <xsd:complexType>
                       <xsd:sequence>
                           <xsd:element name="visualParameters">
                                <xsd:complexType>
                                    <xsd:simpleContent>
                                        <xsd:extension base="xsd:string">
                                            <xsd:attribute name="stem_color" >
                                                <xsd:simpleType>
                                                    <xsd:restriction base="xsd:token">
                                                        <xsd:pattern value="#[\dA-F]{6}([\dA-F][\dA-F])?"/>
                                                    </xsd:restriction>
                                                </xsd:simpleType>
                                            </xsd:attribute>
                                            <xsd:attribute name="leaf_color">
                                                <xsd:simpleType>
                                                    <xsd:restriction base="xsd:token">
                                                        <xsd:pattern value="#[\dA-F]{6}([\dA-F][\dA-F])?"/>
                                                    </xsd:restriction>
                                                </xsd:simpleType>
                                            </xsd:attribute>
                                            <xsd:attribute name="size">
                                                <xsd:simpleType>
                                                    <xsd:restriction base="xsd:string">
                                                        <xsd:pattern value="VERY_SMALL|SMALL|MEDIUM|BIG|VERY_BIG"/>
                                                    </xsd:restriction>
                                                </xsd:simpleType>
                                            </xsd:attribute>
                                        </xsd:extension>
                                    </xsd:simpleContent>
                                </xsd:complexType>
                           </xsd:element>
                           <xsd:element name="growingTips">
                                <xsd:complexType>
                                    <xsd:attribute name="temperature" type="xsd:float"/>
                                    <xsd:attribute name="is_photophilous" type="xsd:boolean"/>
                                    <xsd:attribute name="watering" type="xsd:float"/>
                                </xsd:complexType>
                           </xsd:element>
                           <xsd:element name="multiplying">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="BY_LEAVES|BY_CUTTINGS|BY_SEEDS"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                       </xsd:sequence>
                        <xsd:attribute name="flowerID" type="xsd:ID"/>
                        <xsd:attribute name="name" type="xsd:NCName"/>
                        <xsd:attribute name="soil">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                    <xsd:pattern value="PODZOLIC|GROUND|SODDY_PODZOLIC"/>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:attribute>
                        <xsd:attribute name="origin" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== vernik03/Greenhouse/out/production/Greenhouse/com/lab2/Flowers.xml
<?xml version="1.0"?>
<Flowers>
    <Flower xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="Flowers.xsd">
        <name>Tulip</name>
        <flowerID>2</flowerID>
        <soil>PODZOLIC</soil>
        <origin>Netherlands</origin>
        <visualParameters>
            <stem_color>#FFFF00</stem_color>
            <leaf_color>#00FF00</leaf_color>
            <size>SMALL</size>
        </visualParameters>
        <growingTips>
            <temperature>20</temperature>
            <is_photophilous>true</is_photophilous>
            <watering>10</watering>
        </growingTips>
        <multiplying>BY_SEEDS</multiplying>
    </Flower>
    <Flower xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="Flowers.xsd">
        <name>Roze</name>
        <flowerID>1</flowerID>
        <soil>GROUND</soil>
        <origin>Ukraine</origin>
        <visualParameters>
            <stem_color>#FF0000</stem_color>
            <leaf_color>#00FF00</leaf_color>
            <size>MEDIUM</size>
        </visualParameters>
        <growingTips>
            <temperature>15</temperature>
            <is_photophilous>true</is_photophilous>
            <watering>10</watering>
        </growingTips>
        <multiplying>BY_CUTTINGS</multiplying>
    </Flower>
</Flowers>
